version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on: 
      - php7fpm
      - mysql

  php7fpm:
    image: grodrigo/docker-phplaravel
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql

  artisan:
    image: grodrigo/docker-phplaravel
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql
    entrypoint: ["php", "artisan"]

  composer:  
    image: composer:1.9.1
    working_dir: /var/www
    volumes:
      - ./www:/var/www

  nodejs:
    image: node:13.6-alpine
    volumes:
      - ./www:/var/www
    working_dir: /var/www

  mysql:
    image: mariadb:10.3
    volumes:
      - db_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./backups:/backups
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_INITDB_SKIP_TZINFO=1
    ports:
        - "33061:3306"

volumes:
  db_data:
