version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on: 
      - php7fpm
      - mysql

  artisan:
    image: wiwatsrt/docker-laravel-artisan
    volumes:
      - ./www:/var/www
    depends_on: 
      - mysql

  composer:  
    image: wiwatsrt/docker-laravel-composer
    volumes:
      - ./www:/var/www

  php7fpm:
    image: wiwatsrt/docker-laravel-php7fpm
    volumes:
      - ./www:/var/www
    depends_on: 
      - mysql

  mysql:
    image: mariadb:10.3
    volumes:
      - db_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  nodejs:  
    image: wiwatsrt/docker-laravel-nodejs
    volumes:
      - ./www:/var/www

  composer:
    image: wiwatsrt/docker-laravel-composer
    volumes:
      - ./www:/var/www

volumes:
  db_data:
