version: "3"

networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK}/24

version: '3'
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on: 
      - php7fpm
      - mysql
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}.${VIRTUAL_FQDN}
    networks:
      default:
        ipv4_address: ${SUBNETWORK}.80

  artisan:
    image: wiwatsrt/docker-laravel-artisan
    volumes:
      - ./www:/var/www
    depends_on: 
      - mysql

  composer:  
    image: wiwatsrt/docker-laravel-composer
    volumes:
      - ./www:/var/www

  php7fpm:
    image: wiwatsrt/docker-laravel-php7fpm
    volumes:
      - ./www:/var/www
    depends_on: 
      - mysql

  mysql:
    image: mariadb:10.3
    volumes:
      - ./db_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./backups:/backups
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_INITDB_SKIP_TZINFO=1

  nodejs:  
    image: wiwatsrt/docker-laravel-nodejs
    volumes:
      - ./www:/var/www

##### c9  #####
  c9:
    image: juanitomint/c9collab:php
    depends_on:
      - web
    volumes:
      - ./www:/var/www
      - ./.ssh/:/root/.ssh
      - ./config/user.settings:/root/.c9/user.settings
      #- ./config/.gitconfig:/root/.gitconfig
    environment:
      - VIRTUAL_HOST=c9.${VIRTUAL_HOST}.${VIRTUAL_FQDN}
      - C9_WORKSPACE=/var/www
      - C9_USER=${C9_USER}
      - C9_PASSWD={C9_PASSWD}
    networks:
       default:
        ipv4_address: ${SUBNETWORK}.91

##### PHPMyAdmin  ####
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - VIRTUAL_HOST=myadmin.${VIRTUAL_HOST}.${VIRTUAL_FQDN}

#volumes:
#  db_data:
